name: Build and Test

on:
  push:
    branches: [ master, heroku ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: notebookdb
        postgresql user: dbuser
        postgresql password: dbpasswd
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        JDBC_DATABASE_URL: 'jdbc:postgresql://localhost:5432/notebookdb?user=dbuser&password=dbpasswd'
        PORT: 7000
        AWS_ENABLE: FALSE
      run: ./gradlew build
